services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    environment:
        DATABASE_URL: postgresql://root:root@postgres:5432/tasks-db?schema=public
    networks:
      - dev

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

networks:

  dev:
    driver: bridge

volumes:

  postgres_data:
